PMM-1561 Rollback Consul to 0.8.5.

diff --git a/vendor/github.com/hashicorp/consul/GNUmakefile b/vendor/github.com/hashicorp/consul/GNUmakefile
--- a/vendor/github.com/hashicorp/consul/GNUmakefile
+++ b/vendor/github.com/hashicorp/consul/GNUmakefile
@@ -2,14 +2,10 @@ SHELL = bash
 GOTOOLS = \
 	github.com/elazarl/go-bindata-assetfs/... \
 	github.com/jteeuwen/go-bindata/... \
-	github.com/magiconair/vendorfmt/cmd/vendorfmt \
 	github.com/mitchellh/gox \
 	golang.org/x/tools/cmd/cover \
-	golang.org/x/tools/cmd/stringer \
-	github.com/axw/gocov/gocov \
-	gopkg.in/matm/v1/gocov-html
-
-GOTAGS ?=
+	golang.org/x/tools/cmd/stringer
+GOTAGS ?= consul
 GOFILES ?= $(shell go list ./... | grep -v /vendor/)
 GOOS=$(shell go env GOOS)
 GOARCH=$(shell go env GOARCH)
@@ -31,25 +27,13 @@ bin: tools
 	@GOTAGS='$(GOTAGS)' sh -c "'$(CURDIR)/scripts/build.sh'"
 
 # dev creates binaries for testing locally - these are put into ./bin and $GOPATH
-dev: changelogfmt vendorfmt dev-build
-
-dev-build:
-	@echo "--> Building consul"
+dev:
 	mkdir -p pkg/$(GOOS)_$(GOARCH)/ bin/
 	go install -ldflags '$(GOLDFLAGS)' -tags '$(GOTAGS)'
 	cp $(GOPATH)/bin/consul bin/
 	cp $(GOPATH)/bin/consul pkg/$(GOOS)_$(GOARCH)
 
-vendorfmt:
-	@echo "--> Formatting vendor/vendor.json"
-	test -x $(GOPATH)/bin/vendorfmt || go get -u github.com/magiconair/vendorfmt/cmd/vendorfmt
-	vendorfmt
-
-changelogfmt:
-	@echo "--> Making [GH-xxxx] references clickable..."
-	@sed -E 's|([^\[])\[GH-([0-9]+)\]|\1[[GH-\2](https://github.com/hashicorp/consul/issues/\2)]|g' CHANGELOG.md > changelog.tmp && mv changelog.tmp CHANGELOG.md
-
-# linux builds a linux package independent of the source platform
+# linux builds a linux package indpendent of the source platform
 linux:
 	mkdir -p pkg/linux_amd64/
 	GOOS=linux GOARCH=amd64 go build -ldflags '$(GOLDFLAGS)' -tags '$(GOTAGS)' -o pkg/linux_amd64/consul
@@ -62,33 +46,17 @@ cov:
 	gocov test $(GOFILES) | gocov-html > /tmp/coverage.html
 	open /tmp/coverage.html
 
-test: other-consul porter dev-build vet
-	@echo "--> Running go test"
-	@rm -f test.log exit-code
-	go test -tags '$(GOTAGS)' -i ./...
-	porter go test $(GOTEST_FLAGS) -tags '$(GOTAGS)' -timeout 5m -v ./... &>test.log ; echo $$? > exit-code
-	@echo "Exit code: $$(cat exit-code)" >> test.log
-	@grep -A5 'DATA RACE' test.log || true
-	@grep -A10 'panic: test timed out' test.log || true
-	@grep -A1 -- '--- SKIP:' test.log || true
-	@grep -A1 -- '--- FAIL:' test.log || true
-	@grep '^FAIL' test.log || true
-	@test "$$TRAVIS" == "true" && cat test.log || true
-	@if [ "$$(cat exit-code)" == "0" ] ; then echo "PASS" ; exit 0 ; else exit 1 ; fi
+test: dev
+	go test -tags "$(GOTAGS)" -i ./...
+	go test -tags "$(GOTAGS)" -run '^$$' ./... > /dev/null
+	go test -tags "$(GOTAGS)" -v $$(go list ./... | egrep -v '(agent/consul|vendor)') > test.log 2>&1 || echo 'FAIL_TOKEN' >> test.log
+	go test -tags "$(GOTAGS)" -v $$(go list ./... | egrep '(agent/consul)') >> test.log 2>&1 || echo 'FAIL_TOKEN' >> test.log
+	@if [ "$$TRAVIS" == "true" ] ; then cat test.log ; fi
+	@if grep -q 'FAIL_TOKEN' test.log ; then grep 'FAIL:' test.log ; exit 1 ; else echo 'PASS' ; fi
 
-test-race:
-	$(MAKE) GOTEST_FLAGS=-race
-
-other-consul:
-	@echo "--> Checking for other consul instances"
-	@if ps -ef | grep 'consul agent' | grep -v grep ; then \
-		echo "Found other running consul agents. This may affect your tests." ; \
-		exit 1 ; \
-	fi
-
-porter:
-	@echo "--> Building port number service..."
-	go install github.com/hashicorp/consul/test/porter/cmd/porter
+test-race: dev
+	go test -tags "$(GOTAGS)" -i -run '^$$' ./...
+	( set -o pipefail ; go test -race -tags "$(GOTAGS)" -v ./... 2>&1 | tee test-race.log )
 
 cover:
 	go test $(GOFILES) --cover
@@ -123,4 +91,4 @@ static-assets:
 tools:
 	go get -u -v $(GOTOOLS)
 
-.PHONY: all ci bin dev dist cov test cover format vet ui static-assets tools vendorfmt
+.PHONY: all ci bin dev dist cov test cover format vet ui static-assets tools
