PMM-12738 Print all errors together.

diff --git a/update/ansible/playbook/tasks/roles/nginx/files/ssl/generate-ssl-certificate b/update/ansible/playbook/tasks/roles/nginx/files/ssl/generate-ssl-certificate
--- a/update/ansible/playbook/tasks/roles/nginx/files/ssl/generate-ssl-certificate
+++ b/update/ansible/playbook/tasks/roles/nginx/files/ssl/generate-ssl-certificate
@@ -5,32 +5,39 @@ set -o errexit
 mkdir -p /srv/nginx
 if [ ! -w "/srv/nginx" ]; then
     echo "Directory /srv/nginx is not writable";
+    error=false
     if [ ! -e /srv/nginx/certificate.key ]
     then
-        echo "The file /srv/nginx/certificate.key does not exist. Exiting...";
-        exit 1;
+        echo "The file /srv/nginx/certificate.key does not exist." >&2
+        error=true
     fi
 
     if [ ! -e /srv/nginx/certificate.crt ]
     then
-        echo "The file /srv/nginx/certificate.crt does not exist. Exiting...";
-        exit 1;
+        echo "The file /srv/nginx/certificate.crt does not exist." >&2
+        error=true
     fi
 
     if [ ! -e /srv/nginx/ca-certs.pem ]
     then
-        echo "The file /srv/nginx/ca-certs.pem does not exist. Exiting...";
-        exit 1;
+        echo "The file /srv/nginx/ca-certs.pem does not exist." >&2
+        error=true
     fi
 
     if [ ! -e /srv/nginx/dhparam.pem ]
     then
-        echo "The file /srv/nginx/dhparam.pem does not exist. Exiting...";
-        exit 1;
+        echo "The file /srv/nginx/dhparam.pem does not exist." >&2
+        error=true
     fi
 
-    echo "Using existing self-signed certificate";
-    exit 0;
+    if [ "$error" = true ]
+    then
+        echo "Exiting due to missing file(s)." >&2
+        exit 1;
+    else
+        echo "Using existing self-signed certificate.";
+        exit 0;
+    fi
 fi
 
 if [ ! -e /srv/nginx/dhparam.pem ]; then
