PMM-12899 refactor the directory structure

diff --git a/build/scripts/build-client-packages b/build/scripts/build-client-packages
--- a/build/scripts/build-client-packages
+++ b/build/scripts/build-client-packages
@@ -8,7 +8,7 @@ shell_quote_string() {
 }
 
 usage () {
-    cat <<EOF
+  cat <<EOF
 Usage: $0 [OPTIONS]
     The following options may be given :
         --build_src_rpm     If it is 1 src rpm will be built
@@ -20,7 +20,8 @@ Usage: $0 [OPTIONS]
         --help)             Display this help
 Example $0 --build_src_rpm=1 --build_rpm=1
 EOF
-    exit 1
+
+  exit 1
 }
 
 append_arg_to_args () {
@@ -28,118 +29,89 @@ append_arg_to_args () {
 }
 
 parse_arguments() {
-    WORKDIR=/tmp/pmm
-    for arg do
-        val=`echo "$arg" | sed -e 's;^--[^=]*=;;'`
-        optname=`echo "$arg" | sed -e 's/^\(--[^=]*\)=.*$/\1/'`
-        case "$arg" in
-            --build_src_rpm=*) SRPM="$val" ;;
-            --build_rpm=*) RPM="$val" ;;
-            --build_source_deb=*) SDEB="$val" ;;
-            --build_deb=*) DEB="$val" ;;
-            --branch=*) SUBMODULE_BRANCH="$val" ;;
-            --install_deps=*) INSTALL="$val" ;;
-            --help) usage ;;
-            *) append_arg_to_args "$arg" ;;
-        esac
-    done
-}
-
-get_branches() {
-    COMPONENT=$1
-    if [ ! -e ${WORKDIR}/pmm-submodules ]; then
-        git clone https://github.com/Percona-Lab/pmm-submodules.git ${WORKDIR}/pmm-submodules 1>&2
-    fi
-    cd ${WORKDIR}/pmm-submodules
-      git reset --hard > /dev/null 2>&1
-      git clean -xdf > /dev/null 2>&1
-      git checkout $SUBMODULE_BRANCH
-      # this is the return value of this function
-      git submodule status | grep $COMPONENT | awk '{print $1}' | awk -F'-' '{print $2}'
-    cd - >/dev/null
-}
-
-get_repos() {
-    COMPONENT=$1
-    if [ ! -e ${WORKDIR}/pmm-submodules ]; then
-        git clone https://github.com/Percona-Lab/pmm-submodules.git ${WORKDIR}/pmm-submodules
-    fi
-    cd ${WORKDIR}/pmm-submodules
-      git reset --hard > /dev/null 2>&1
-      git clean -xdf > /dev/null 2>&1
-      git checkout $SUBMODULE_BRANCH > /dev/null 2>&1
-      grep -A 3 "\[submodule \"${COMPONENT}\"\]" .gitmodules | grep "url" | awk '{print $3}'
-    cd - >/dev/null
+  WORKDIR=/tmp/pmm
+  for arg do
+    val=`echo "$arg" | sed -e 's;^--[^=]*=;;'`
+    optname=`echo "$arg" | sed -e 's/^\(--[^=]*\)=.*$/\1/'`
+    case "$arg" in
+      --build_src_rpm=*) SRPM="$val" ;;
+      --build_rpm=*) RPM="$val" ;;
+      --build_source_deb=*) SDEB="$val" ;;
+      --build_deb=*) DEB="$val" ;;
+      --branch=*) SUBMODULE_BRANCH="$val" ;;
+      --install_deps=*) INSTALL="$val" ;;
+      --help) usage ;;
+      *) append_arg_to_args "$arg" ;;
+    esac
+  done
 }
 
 check_workdir(){
-    if [ "$WORKDIR" = "$CURDIR" ]; then
-        echo >&2 "Current directory cannot be used for building!"
-        exit 1
-    fi
-    
-    if ! test -d "$WORKDIR"; then
-        mkdir -p "$WORKDIR"
-    fi
+  if [ "$WORKDIR" = "$CURDIR" ]; then
+    echo >&2 "Current directory cannot be used for building!"
+    exit 1
+  fi
+  
+  if ! test -d "$WORKDIR"; then
+    mkdir -p "$WORKDIR"
+  fi
 }
 
 get_system(){
-    if [ -f /etc/redhat-release ]; then
-        RHEL=$(rpm --eval %rhel)
-        ARCH=$(echo $(uname -m) | sed -e 's:i686:i386:g')
-        OS_NAME="el$RHEL"
-        OS="rpm"
-    else
-        ARCH=$(uname -m)
-        OS_NAME="$(lsb_release -sc)"
-        OS="deb"
-    fi
-    return
+  if [ -f /etc/redhat-release ]; then
+    RHEL=$(rpm --eval %rhel)
+    ARCH=$(echo $(uname -m) | sed -e 's:i686:i386:g')
+    OS_NAME="el$RHEL"
+    OS="rpm"
+else
+    ARCH=$(uname -m)
+    OS_NAME="$(lsb_release -sc)"
+    OS="deb"
+  fi
 }
 
 install_deps() {
-    local PACKAGES
-    if [ $INSTALL = 0 ]; then
-        echo "Dependencies will not be installed."
-        return;
-    fi
-    if [ $(id -u) -ne 0 ]; then
-        echo "It is not possible to install dependencies. Please run as root."
-        exit 1
-    fi
-    if [ "$OS" = "rpm" ]; then
-        # yum -y install git curl wget rpmdevtools bison yum-utils rpm-build
-        command -v git || PACKAGES+=" git"
-        command -v curl || PACKAGES+=" curl"
-        command -v wget || PACKAGES+=" wget"
-        command -v spectool || PACKAGES+=" rpmdevtools"
-        command -v bison || PACKAGES+=" bison"
-        command -v repoquery || PACKAGES+=" yum-utils"
-        command -v rpmbuild || PACKAGES+=" rpm-build"
-        if [ -n "$PACKAGES" ]; then
-            yum -y install "$PACKAGES"
-        fi
-    else
-        apt-get update
-        apt-get -y install devscripts equivs debhelper
-    fi
+  local PACKAGES
+  if [ $INSTALL = 0 ]; then
+    echo "Dependencies will not be installed."
     return;
+  fi
+  if [ $(id -u) -ne 0 ]; then
+    echo "It is not possible to install dependencies. Please run as root."
+    exit 1
+  fi
+  if [ "$OS" = "rpm" ]; then
+    # yum -y install git curl wget rpmdevtools bison yum-utils rpm-build
+    command -v git || PACKAGES+=" git"
+    command -v curl || PACKAGES+=" curl"
+    command -v wget || PACKAGES+=" wget"
+    command -v spectool || PACKAGES+=" rpmdevtools"
+    command -v bison || PACKAGES+=" bison"
+    command -v repoquery || PACKAGES+=" yum-utils"
+    command -v rpmbuild || PACKAGES+=" rpm-build"
+    if [ -n "$PACKAGES" ]; then
+      yum -y install "$PACKAGES"
+    fi
+  else
+    apt-get update
+    apt-get -y install devscripts equivs debhelper
+  fi
 }
 
 get_tar(){
-    local TARBALL=$1
-    local TARFILE=$(basename $(find $WORKDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
+  local TARBALL=$1
+  local TARFILE=$(basename $(find $WORKDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
+  if [ -z $TARFILE ]; then
+    TARFILE=$(basename $(find $CURDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
     if [ -z $TARFILE ]; then
-        TARFILE=$(basename $(find $CURDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
-        if [ -z $TARFILE ]; then
-            echo "There is no $TARBALL for build"
-            exit 1
-        else
-            cp $CURDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
-        fi
+      echo "There is no $TARBALL for build"
+      exit 1
     else
-        cp $WORKDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
+      cp $CURDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
     fi
+  else
+    cp $WORKDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
+  fi
 }
 
 get_deb_sources(){
@@ -161,84 +133,84 @@ get_deb_sources(){
 }
 
 build_srpm(){
-    if [ "$OS" = "deb" ]; then
-        echo "It is not possible to build src rpm here"
-        exit 1
-    fi
-    cd $WORKDIR
-    get_tar "tarball"
+  if [ "$OS" = "deb" ]; then
+    echo "It is not possible to build src rpm here"
+    exit 1
+  fi
+  cd $WORKDIR
+  get_tar "tarball"
 
-    rm -fr rpmbuild
-    ls | grep -v tar.gz | xargs rm -rf
+  rm -fr rpmbuild
+  ls | grep -v tar.gz | xargs rm -rf
 
-    TARFILE=$(basename $(find . -name "${PACKAGE_NAME}-*.tar.gz" | sort | tail -n1))
-    NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
-    VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
-    VERSION=${VERSION_TMP%.tar.gz}
+  TARFILE=$(basename $(find . -name "${PACKAGE_NAME}-*.tar.gz" | sort | tail -n1))
+  NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
+  VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
+  VERSION=${VERSION_TMP%.tar.gz}
 
-    mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
+  mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
 
-    tar -C ${WORKDIR} -zxpf ${TARFILE} ${NAME}-${VERSION}/rpm
+  tar -C ${WORKDIR} -zxpf ${TARFILE} ${NAME}-${VERSION}/rpm
 
-    cd ${WORKDIR}/rpmbuild/SPECS
-    cp ${WORKDIR}/${NAME}-${VERSION}/rpm/*.spec .
-    cp ${WORKDIR}/${TARFILE} ../SOURCES/
-    cd ${WORKDIR}
-    rpmbuild -bs \
-      --define "_topdir ${WORKDIR}/rpmbuild" \
-      --define "version $VERSION" \
-      --define "release $RPM_RELEASE" \
-      --define "dist %{nil}" \
-      "rpmbuild/SPECS/${PACKAGE_NAME}.spec"
+  cd ${WORKDIR}/rpmbuild/SPECS
+  cp ${WORKDIR}/${NAME}-${VERSION}/rpm/*.spec .
+  cp ${WORKDIR}/${TARFILE} ../SOURCES/
+  cd ${WORKDIR}
+  rpmbuild -bs \
+    --define "_topdir ${WORKDIR}/rpmbuild" \
+    --define "version $VERSION" \
+    --define "release $RPM_RELEASE" \
+    --define "dist %{nil}" \
+    "rpmbuild/SPECS/${PACKAGE_NAME}.spec"
 
-    mkdir -p ${WORKDIR}/srpm
-    mkdir -p ${CURDIR}/srpm
-    cp rpmbuild/SRPMS/*.src.rpm ${CURDIR}/srpm
-    cp rpmbuild/SRPMS/*.src.rpm ${WORKDIR}/srpm
+  mkdir -p ${WORKDIR}/srpm
+  mkdir -p ${CURDIR}/srpm
+  cp rpmbuild/SRPMS/*.src.rpm ${CURDIR}/srpm
+  cp rpmbuild/SRPMS/*.src.rpm ${WORKDIR}/srpm
 }
 
 build_rpm(){
-    if [ "$OS" = "deb" ]; then
-        echo "It is not possible to build rpm here"
-        exit 1
-    fi
+  if [ "$OS" = "deb" ]; then
+    echo "It is not possible to build rpm here"
+    exit 1
+  fi
 
-    SRC_RPM=$(basename $(find $WORKDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
+  SRC_RPM=$(basename $(find $WORKDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
+  if [ -z $SRC_RPM ]; then
+    SRC_RPM=$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
     if [ -z $SRC_RPM ]; then
-        SRC_RPM=$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
-        if [ -z $SRC_RPM ]; then
-            echo "There is no src rpm for build"
-            echo "You can create it using key --build_src_rpm=1"
-            exit 1
-        else
-            cp $CURDIR/srpm/$SRC_RPM $WORKDIR
-        fi
+      echo "There is no src rpm for build"
+      echo "You can create it using key --build_src_rpm=1"
+      exit 1
     else
-        cp $WORKDIR/srpm/$SRC_RPM $WORKDIR
+      cp $CURDIR/srpm/$SRC_RPM $WORKDIR
     fi
+  else
+    cp $WORKDIR/srpm/$SRC_RPM $WORKDIR
+  fi
 
-    cd $WORKDIR
-    rm -fr rpmbuild
-    mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
-    cp $SRC_RPM rpmbuild/SRPMS/
-    if find "${CURDIR}/rpm" -name "${PACKAGE_NAME}-${pmm_version}-*.rpm"; then
-        # Remove older client rpm packages before building a new one
-        rm -f "${CURDIR}/rpm/${PACKAGE_NAME}-${pmm_version}-*.rpm"
-    fi
-    rpmbuild --define "_topdir ${WORKDIR}/rpmbuild" \
-             --define "version $pmm_version" \
-             --define "release $RPM_RELEASE" \
-             --define "dist .$OS_NAME" \
-             --rebuild rpmbuild/SRPMS/$SRC_RPM
+  cd $WORKDIR
+  rm -fr rpmbuild
+  mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
+  cp $SRC_RPM rpmbuild/SRPMS/
+  if find "${CURDIR}/rpm" -name "${PACKAGE_NAME}-${pmm_version}-*.rpm"; then
+    # Remove older client rpm packages before building a new one
+    rm -f "${CURDIR}/rpm/${PACKAGE_NAME}-${pmm_version}-*.rpm"
+  fi
+  rpmbuild --define "_topdir ${WORKDIR}/rpmbuild" \
+            --define "version $pmm_version" \
+            --define "release $RPM_RELEASE" \
+            --define "dist .$OS_NAME" \
+            --rebuild rpmbuild/SRPMS/$SRC_RPM
 
-    return_code=$?
-    if [ "$return_code" -ne 0 ]; then
-        echo "Error: rpmbuild exited with a non-zero return code '$return_code'\n"
-        exit $return_code
-    fi
+  return_code=$?
+  if [ "$return_code" -ne 0 ]; then
+    echo "Error: rpmbuild exited with a non-zero return code '$return_code'\n"
+    exit $return_code
+  fi
 
-    mkdir -p ${CURDIR}/rpm
-    cp rpmbuild/RPMS/*/*.rpm ${CURDIR}/rpm
+  mkdir -p ${CURDIR}/rpm
+  cp rpmbuild/RPMS/*/*.rpm ${CURDIR}/rpm
 }
 
 build_source_deb(){
@@ -394,4 +366,4 @@ if [ "$DEB" != 0 ]; then
   build_deb
 fi
 
-# vim: expandtab shiftwidth=4 tabstop=4
+# vim: expandtab shiftwidth=2 tabstop=2
