PMM-13487 simplify build-client-packages

diff --git a/build/scripts/build-client-packages b/build/scripts/build-client-packages
--- a/build/scripts/build-client-packages
+++ b/build/scripts/build-client-packages
@@ -1,11 +1,8 @@
 #!/bin/sh
+# NOTE: this script is always executed in a container environment.
 
 set -o errexit
 set -o xtrace
-
-shell_quote_string() {
-  echo "$1" | sed -e 's,\([^a-zA-Z0-9/_.=-]\),\\\1,g'
-}
 
 usage () {
   cat <<EOF
@@ -61,12 +58,6 @@ else
 
 get_tar(){
   local TARBALL=$1
-  # local TARFILE=$(basename $(find $WORKDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
-  # if [ -n $TARFILE ]; then
-  #   cp $WORKDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
-  #   return
-  # fi
-
   local TARFILE=$(basename $(find $CURDIR/$TARBALL -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1) || :)
   if [ -n $TARFILE ]; then
     cp $CURDIR/$TARBALL/$TARFILE $WORKDIR/$TARFILE
@@ -106,10 +97,10 @@ build_srpm(){
   rm -fr rpmbuild
   ls | grep -v tar.gz | xargs rm -rf
 
-  TARFILE=$(basename $(find . -name "${PACKAGE_NAME}-*.tar.gz" | sort | tail -n1))
-  NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
-  VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
-  VERSION=${VERSION_TMP%.tar.gz}
+  local TARFILE=$(basename $(find . -name "${PACKAGE_NAME}-*.tar.gz" | sort | tail -n1))
+  local NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
+  local VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
+  local VERSION=${VERSION_TMP%.tar.gz}
 
   mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
 
@@ -126,10 +117,10 @@ build_srpm(){
     --define "dist %{nil}" \
     "rpmbuild/SPECS/${PACKAGE_NAME}.spec"
 
-  mkdir -p ${WORKDIR}/srpm
+  # mkdir -p ${WORKDIR}/srpm
   mkdir -p ${CURDIR}/srpm
   cp rpmbuild/SRPMS/*.src.rpm ${CURDIR}/srpm
-  cp rpmbuild/SRPMS/*.src.rpm ${WORKDIR}/srpm
+  # cp rpmbuild/SRPMS/*.src.rpm ${WORKDIR}/srpm
 }
 
 build_rpm(){
@@ -138,24 +129,21 @@ build_rpm(){
     exit 1
   fi
 
-  SRC_RPM=$(basename $(find $WORKDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
-  if [ -z $SRC_RPM ]; then
-    SRC_RPM=$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
-    if [ -z $SRC_RPM ]; then
-      echo "There is no src rpm for build"
-      echo "You can create it using key --build_src_rpm=1"
-      exit 1
-    else
-      cp $CURDIR/srpm/$SRC_RPM $WORKDIR
-    fi
-  else
-    cp $WORKDIR/srpm/$SRC_RPM $WORKDIR
+  local SRC_RPM=$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
+  if [ -z "$SRC_RPM" ]; then
+    echo "Error: no source RPM could be found, exiting..."
+    echo "You can create SRPM using the parameter --build_src_rpm"
+    exit 1
+  # else
+    # rm -f "$CURDIR/srpm/$SRC_RPM" || :
+    # cp "$CURDIR/srpm/$SRC_RPM" "$WORKDIR"
   fi
 
   cd $WORKDIR
   rm -fr rpmbuild
   mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
-  cp $SRC_RPM rpmbuild/SRPMS/
+  cp "$CURDIR/srpm/$SRC_RPM" rpmbuild/SRPMS/
+
   if find "${CURDIR}/rpm" -name "${PACKAGE_NAME}-${pmm_version}-*.rpm"; then
     # Remove older client rpm packages before building a new one
     rm -f "${CURDIR}/rpm/${PACKAGE_NAME}-${pmm_version}-*.rpm"
@@ -262,10 +250,10 @@ build_deb(){
   cd $WORKDIR
   rm -fv *.deb
   export DEBIAN_VERSION="$(lsb_release -sc)"
-  DSC=$(basename $(find . -name '*.dsc' | sort | tail -n 1))
-  DIRNAME=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $1"-"$2}')
-  VERSION=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $3}')
-  ARCH=$(uname -m)
+  local DSC=$(basename $(find . -name '*.dsc' | sort | tail -n 1))
+  local DIRNAME=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $1"-"$2}')
+  local VERSION=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $3}')
+  local ARCH=$(uname -m)
   echo "DEBIAN_VERSION=${DEBIAN_VERSION}" >> $VERSION_FILE
   echo "ARCH=${ARCH}" >> $VERSION_FILE
   #
@@ -282,10 +270,10 @@ build_deb(){
 
 #main
 
-CURDIR=$(pwd)
+CURDIR=$(pwd) # /home/builder/build
+WORKDIR=/tmp/pmm
 PACKAGE_NAME=pmm-client
 VERSION_FILE=$CURDIR/pmm-client.properties
-WORKDIR=/tmp/pmm
 SRPM=0
 SDEB=0
 RPM=0
