PMM-13487 use quotes to prevent word splitting

diff --git a/build/scripts/build-client-packages b/build/scripts/build-client-packages
--- a/build/scripts/build-client-packages
+++ b/build/scripts/build-client-packages
@@ -1,6 +1,12 @@
 #!/bin/sh
 # NOTE: this script must be executed in a container environment.
 
+# Disable some shellcheck warnings - this is a script that runs in a controlled environment
+# shellcheck disable=SC3043 # In POSIX sh, local is undefined.
+# shellcheck disable=SC3044 # In POSIX sh, pushd is undefined.
+# shellcheck disable=SC3009 # In POSIX sh, brace expansion is undefined.
+# shellcheck disable=SC2035 # Use ./*glob* or -- *glob* so names with dashes won't become options.
+
 set -o errexit
 set -o xtrace
 
@@ -57,7 +63,7 @@ check_workdir(){
 
 # Find the tarball and copy it to WORKDIR
 get_tar(){
-  local TARBALL_DIR=$1
+  local TARBALL_DIR="$1"
   local TARFILE=$(basename $(find "$CURDIR/$TARBALL_DIR" -name "${PACKAGE_NAME}*.tar.gz" | sort | tail -n1))
   if [ ! -f "$CURDIR/$TARBALL_DIR/$TARFILE" ]; then
     echo "Error: $TARBALL_DIR could not be found, exiting..."
@@ -69,29 +75,29 @@ get_tar(){
 }
 
 get_deb_sources(){
-  local param=$1
-  local FILE=$(basename $(find $CURDIR/source_deb -name "${PACKAGE_NAME}*.$param" | sort | tail -n1))
-  if [ -z $FILE ]; then
+  local param="$1"
+  local FILE=$(basename $(find "$CURDIR/source_deb" -name "${PACKAGE_NAME}*.$param" | sort | tail -n1))
+  if [ -z "$FILE" ]; then
     echo "There is no source to build from"
     exit 1
   else
-    cp $CURDIR/source_deb/$FILE $WORKDIR/
+    cp "$CURDIR/source_deb/$FILE" "$WORKDIR/"
   fi
 }
 
 build_srpm(){
   local TARFILE=$(get_tar "tarball")
-  local NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
-  local VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
-  local VERSION=${VERSION_TMP%.tar.gz}
+  local NAME=$(echo "${TARFILE}"| awk -F '-' '{print $1"-"$2}')
+  local VERSION_TMP=$(echo "${TARFILE}"| awk -F '-' '{print $3}')
+  local VERSION="${VERSION_TMP%.tar.gz}"
 
   cd $WORKDIR
   mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
 
-  tar -C ${WORKDIR} -zxpf ${TARFILE} ${NAME}-${VERSION}/rpm
+  tar -C ${WORKDIR} -zxpf "${TARFILE}" "${NAME}-${VERSION}/rpm"
 
-  cp ${WORKDIR}/${NAME}-${VERSION}/rpm/*.spec ${WORKDIR}/rpmbuild/SPECS/
-  cp ${WORKDIR}/${TARFILE} ${WORKDIR}/rpmbuild/SOURCES/
+  cp "${WORKDIR}/${NAME}-${VERSION}"/rpm/*.spec "${WORKDIR}/rpmbuild/SPECS/"
+  cp "${WORKDIR}/${TARFILE}" "${WORKDIR}/rpmbuild/SOURCES/"
 
   rpmbuild -bs \
     --define "_topdir ${WORKDIR}/rpmbuild" \
@@ -105,8 +111,10 @@ build_srpm(){
 }
 
 build_rpm(){
-  local SRC_RPM=$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)
-  local RHEL=$(rpm --eval %rhel)
+  local SRC_RPM RHEL
+  SRC_RPM="$(basename $(find $CURDIR/srpm -name "${PACKAGE_NAME}*.src.rpm" | sort | tail -n1) || :)"
+  RHEL="$(rpm --eval %rhel)"
+
   if [ -z "$SRC_RPM" ]; then
     echo "Error: no source RPM could be found, exiting..."
     echo "You can build source RPM using the parameter --build_src_rpm"
@@ -118,19 +126,20 @@ build_rpm(){
   mkdir -vp rpmbuild/{SOURCES,SPECS,BUILD,SRPMS,RPMS}
   cp "$CURDIR/srpm/$SRC_RPM" rpmbuild/SRPMS/
 
-  if find "${CURDIR}/rpm" -name "${PACKAGE_NAME}-${pmm_version}-*.rpm"; then
+  if find "${CURDIR}/rpm" -name "${PACKAGE_NAME}-${PMM_VERSION}-*.rpm"; then
     # Remove older client rpm packages before building a new one
-    rm -f "${CURDIR}/rpm/${PACKAGE_NAME}-${pmm_version}-*.rpm"
+    rm -f "${CURDIR}/rpm/${PACKAGE_NAME}-${PMM_VERSION}-*.rpm"
   fi
   rpmbuild  --define "_topdir ${WORKDIR}/rpmbuild" \
-            --define "version $pmm_version" \
+            --define "version $PMM_VERSION" \
             --define "release $RPM_RELEASE" \
             --define "dist .el${RHEL}" \
-            --rebuild rpmbuild/SRPMS/$SRC_RPM
+            --rebuild "rpmbuild/SRPMS/$SRC_RPM"
 
   return_code=$?
   if [ "$return_code" -ne 0 ]; then
-    echo "Error: rpmbuild exited with a non-zero return code '$return_code'\n"
+    echo "Error: rpmbuild exited with a non-zero return code '$return_code'"
+    echo
     exit $return_code
   fi
 
@@ -142,20 +151,21 @@ build_source_deb(){
   rm -rf pmm-client*
   rm -f *.dsc *.orig.tar.gz *.debian.tar.gz *.changes
 
-  local TARFILE=$(get_tar "tarball")
-  local NAME=$(echo ${TARFILE}| awk -F '-' '{print $1"-"$2}')
-  local VERSION_TMP=$(echo ${TARFILE}| awk -F '-' '{print $3}')
-  local VERSION=${VERSION_TMP%.tar.gz}
+  local TARFILE NAME VERSION_TMP VERSION NEWTAR
+  TARFILE="$(get_tar tarball)"
+  NAME="$(echo "${TARFILE}" | awk -F '-' '{print $1"-"$2}')"
+  VERSION_TMP="$(echo "${TARFILE}" | awk -F '-' '{print $3}')"
+  VERSION="${VERSION_TMP%.tar.gz}"
 
-  rm -fr ${NAME}-${VERSION}
+  rm -fr "${NAME}-${VERSION}"
 
-  NEWTAR=${NAME}_${VERSION}.orig.tar.gz
-  mv ${TARFILE} ${NEWTAR}
+  NEWTAR="${NAME}_${VERSION}.orig.tar.gz"
+  mv "${TARFILE}" "${NEWTAR}"
 
-  git clone $REPO ${NAME}-${VERSION}_all
-  pushd ${NAME}-${VERSION}_all
+  git clone "$REPO" "${NAME}-${VERSION}_all"
+  pushd "${NAME}-${VERSION}_all"
     git fetch origin
-    if [ -n ${BRANCH} ]; then
+    if [ -n "${BRANCH}" ]; then
       git reset --hard
       git clean -xdf
       git checkout ${BRANCH}
@@ -164,25 +174,25 @@ build_source_deb(){
     mkdir distro
   popd
 
-  tar xzf ${NEWTAR}
-  cd ${NAME}-${VERSION}
-  mv bin/* ../${NAME}-${VERSION}_all/distro/
-  mv example.prom ../${NAME}-${VERSION}_all/distro/
-  mv queries-mysqld.yml ../${NAME}-${VERSION}_all/distro/
-  mv queries-mysqld-group-replication.yml ../${NAME}-${VERSION}_all/distro/
-  mv example-queries-postgres.yml ../${NAME}-${VERSION}_all/distro/
-  mv queries-postgres-uptime.yml ../${NAME}-${VERSION}_all/distro/
-  mv queries-mr.yaml ../${NAME}-${VERSION}_all/distro/
-  mv queries-lr.yaml ../${NAME}-${VERSION}_all/distro/
-  mv debian ../${NAME}-${VERSION}_all/
-  mv config/pmm-agent.service ../${NAME}-${VERSION}_all/debian/${PACKAGE_NAME}.pmm-agent.service
+  tar xzf "${NEWTAR}"
+  cd "${NAME}-${VERSION}"
+  mv bin/* ../"${NAME}-${VERSION}"_all/distro/
+  mv example.prom ../"${NAME}-${VERSION}"_all/distro/
+  mv queries-mysqld.yml ../"${NAME}-${VERSION}"_all/distro/
+  mv queries-mysqld-group-replication.yml ../"${NAME}-${VERSION}"_all/distro/
+  mv example-queries-postgres.yml ../"${NAME}-${VERSION}"_all/distro/
+  mv queries-postgres-uptime.yml ../"${NAME}-${VERSION}"_all/distro/
+  mv queries-mr.yaml ../"${NAME}-${VERSION}"_all/distro/
+  mv queries-lr.yaml ../"${NAME}-${VERSION}"_all/distro/
+  mv debian ../"${NAME}-${VERSION}"_all/
+  mv config/pmm-agent.service ../"${NAME}-${VERSION}"_all/debian/${PACKAGE_NAME}.pmm-agent.service
   cd ../
 
-  rm -rf ${NAME}-${VERSION}
-  mv ${NAME}-${VERSION}_all ${NAME}-${VERSION}
+  rm -rf "${NAME}-${VERSION}"
+  mv "${NAME}-${VERSION}"_all "${NAME}-${VERSION}"
   rm -rf *.tar.gz
-  tar -zcvf ${NEWTAR} ${NAME}-${VERSION}
-  cd ${NAME}-${VERSION}
+  tar -zcvf "${NEWTAR}" "${NAME}-${VERSION}"
+  cd "${NAME}-${VERSION}"
   sed -i "s/%{version}/$VERSION-$DEB_RELEASE/" debian/control
 
   cd debian
@@ -195,16 +205,16 @@ build_source_deb(){
   dch -D unstable --force-distribution -v "${VERSION}-${DEB_RELEASE}" "Update to new upstream release of PMM Client ${VERSION}-${DEB_RELEASE}"
   dpkg-buildpackage -S
   cd ../
-  mkdir -p $WORKDIR/source_deb
-  mkdir -p $CURDIR/source_deb
-  cp *.diff.gz $WORKDIR/source_deb
-  cp *_source.changes $WORKDIR/source_deb
-  cp *.dsc $WORKDIR/source_deb
-  cp *.orig.tar.gz $WORKDIR/source_deb
-  cp *.diff.gz $CURDIR/source_deb
-  cp *_source.changes $CURDIR/source_deb
-  cp *.dsc $CURDIR/source_deb
-  cp *.orig.tar.gz $CURDIR/source_deb
+  mkdir -p "$WORKDIR/source_deb"
+  mkdir -p "$CURDIR/source_deb"
+  cp *.diff.gz "$WORKDIR/source_deb"
+  cp *_source.changes "$WORKDIR/source_deb"
+  cp *.dsc "$WORKDIR/source_deb"
+  cp *.orig.tar.gz "$WORKDIR/source_deb"
+  cp *.diff.gz "$CURDIR/source_deb"
+  cp *_source.changes "$CURDIR/source_deb"
+  cp *.dsc "$CURDIR/source_deb"
+  cp *.orig.tar.gz "$CURDIR/source_deb"
 }
 
 build_deb(){
@@ -214,21 +224,22 @@ build_deb(){
 
   cd $WORKDIR
   rm -fv *.deb
-  export DEBIAN_VERSION="$(lsb_release -sc)"
-  local DSC=$(basename $(find . -name '*.dsc' | sort | tail -n 1))
-  local DIRNAME=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $1"-"$2}')
-  local VERSION=$(echo ${DSC} | sed -e 's:_:-:g' | awk -F'-' '{print $3}')
-  local ARCH=$(uname -m)
-  echo "DEBIAN_VERSION=${DEBIAN_VERSION}" >> $VERSION_FILE
-  echo "ARCH=${ARCH}" >> $VERSION_FILE
+  local DEBIAN_VERSION DSC DIRNAME VERSION ARCH
+  DEBIAN_VERSION="$(lsb_release -sc)"
+  DSC=$(basename "$(find . -name '*.dsc' | sort | tail -n 1)")
+  DIRNAME=$(echo "${DSC}" | sed -e 's:_:-:g' | awk -F'-' '{print $1"-"$2}')
+  VERSION=$(echo "${DSC}" | sed -e 's:_:-:g' | awk -F'-' '{print $3}')
+  ARCH=$(uname -m)
+  echo "DEBIAN_VERSION=${DEBIAN_VERSION}" >> "$VERSION_FILE"
+  echo "ARCH=${ARCH}" >> "$VERSION_FILE"
   #
-  dpkg-source -x ${DSC}
-  cd ${DIRNAME}-${VERSION}
+  dpkg-source -x "${DSC}"
+  cd "${DIRNAME}-${VERSION}"
   dch -b -m -D "$DEBIAN_VERSION" --force-distribution -v "${VERSION}-${DEB_RELEASE}.${DEBIAN_VERSION}" 'Update distribution'
 
   dpkg-buildpackage -rfakeroot -uc -us -b
-  mkdir -p $CURDIR/deb
-  cp $WORKDIR/*.deb $CURDIR/deb
+  mkdir -p "$CURDIR/deb"
+  cp $WORKDIR/*.deb "$CURDIR/deb"
 }
 
 main() {
@@ -237,16 +248,11 @@ main() {
   WORKDIR=/tmp/pmm
   PACKAGE_NAME=pmm-client
   VERSION_FILE=${CURDIR}/${PACKAGE_NAME}.properties
-  RPM_RELEASE=1
-  DEB_RELEASE=1
+  RPM_RELEASE=${pmm_release:-1}
+  DEB_RELEASE=${pmm_release:-1}
   REVISION=0
   BRANCH="v3"
   REPO="https://github.com/Percona-Lab/pmm-submodules.git"
-
-  if [ -n "$pmm_release" ]; then
-    RPM_RELEASE="$pmm_release"
-    DEB_RELEASE="$pmm_release"
-  fi
 
   check_workdir
 
