PMM-12913 migrate /v1/management/Service

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,17 +81,18 @@ jobs:
 
       - name: Run API linter
         env:
-          COMMAND: 'bin/buf lint -v api'
-          REDIRECT: "| bin/reviewdog -f=buf -reporter=github-pr-review -fail-on-error=true"
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
         run: |
-          if out=$( ${{ env.COMMAND }} ); exit_code=$?; [ $exit_code -ne 0 ]; then
+          if out=$(bin/buf lint -v api); code="$?"; test "$code" -ne 0; then
+            echo "API linter exited with code: $code"
+            echo "$out"
             ## buf uses exit code 100 for linter warnings
-            if [ $exit_code != 100 ] || ${{ github.event.pull_request == null }}; then
-              echo "$out"
-              exit $exit_code
+            if [ "$code" -ne 100 ] || ${{ github.event.pull_request == null }}; then
+              exit $code
             else
-              echo "$out" ${{ env.REDIRECT }}
+              echo
+              # suppress passing to reviewdog because of https://github.com/reviewdog/reviewdog/issues/1696
+              # echo "$out" | bin/reviewdog -f=buf -reporter=github-pr-review -fail-on-error=true
             fi
           else
             echo "$out"
