PMM-7 Modernize go tools

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,12 +47,7 @@ jobs:
             ${{ runner.os }}-go-modules-
 
       - name: Download Go modules
-        run: |
-          pushd tools && go mod download -x
-          popd        && go mod download -x
-
-      - name: Install development tools
-        run: make init
+        run: go mod download -x
 
       - name: Generate files
         run: make gen
@@ -63,8 +58,7 @@ jobs:
       - name: Check files are formatted and no source code changes
         run: |
           make format
-          pushd tools && go mod tidy -v
-          popd        && go mod tidy -v
+          go mod tidy -v
           git status
           git diff --exit-code
 
@@ -77,16 +71,16 @@ jobs:
       - name: Run check-license
         run: |
           # run license checker on configured files
-          bin/license-eye -c .licenserc.yaml header check
+          go tool license-eye -c .licenserc.yaml header check
 
       - name: Run go-sumtype
-        run: bin/go-sumtype ./...
+        run: go tool go-sumtype ./...
 
       - name: Run API linter
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
         run: |
-          if out=$(bin/buf lint -v api); code="$?"; test "$code" -eq 0; then
+          if out=$(go tool buf lint -v api); code="$?"; test "$code" -eq 0; then
             echo "$out"
             exit 0
           fi
@@ -99,7 +93,7 @@ jobs:
           fi
 
           # One may need to suppress passing to reviewdog because of https://github.com/reviewdog/reviewdog/issues/1696
-          echo "$out" | bin/reviewdog -f=buf -reporter=github-pr-review -fail-level=error
+          echo "$out" | go tool reviewdog -f=buf -reporter=github-pr-review -fail-level=error
 
       - name: Run code linters
         uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2.8.0
@@ -116,7 +110,7 @@ jobs:
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
         run: |
-          if out=$(bin/go-consistent -pedantic -exclude "tests" ./...); exit_code=$?; [ $exit_code -eq 0 ]; then
+          if out=$(go tool go-consistent -pedantic -exclude "tests" ./...); exit_code=$?; [ $exit_code -eq 0 ]; then
             echo "$out"
             exit 0
           fi
@@ -126,7 +120,7 @@ jobs:
             exit $exit_code
           fi
 
-          echo "$out" | bin/reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error
+          echo "$out" | go tool reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error
 
       - name: Test common API
         run: make test-common
