PMM-12913 move dump and role API to v1beta1 folder

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -80,26 +80,23 @@ jobs:
         run: bin/go-sumtype ./...
 
       - name: Run API linter
-        # TODO: re-enable before merging!
-        if: false
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
         run: |
-          if out=$(bin/buf lint -v api); code="$?"; test "$code" -ne 0; then
-            echo "API linter exited with code: $code"
+          if out=$(bin/buf lint -v api); code="$?"; test "$code" -eq 0; then
             echo "$out"
-            ## buf uses exit code 100 for linter warnings
-            if [ "$code" -ne 100 ] || ${{ github.event.pull_request == null }}; then
-              exit $code
-            else
-              echo
-              # Suppress passing to reviewdog because of https://github.com/reviewdog/reviewdog/issues/1696
-              # TODO: re-enable before merging to v3
-              # echo "$out" | bin/reviewdog -f=buf -reporter=github-pr-review -fail-on-error=true
-            fi
-          else
-            echo "$out"
+            exit 0
           fi
+
+          echo "API linter exited with code: $code"
+          echo "$out"
+          ## buf uses exit code 100 for linter warnings
+          if [ "$code" -ne 100 ] || ${{ github.event.pull_request == null }}; then
+            exit $code
+          fi
+
+          # One may need to suppress passing to reviewdog because of https://github.com/reviewdog/reviewdog/issues/1696
+          echo "$out" | bin/reviewdog -f=buf -reporter=github-pr-review -fail-on-error=true
 
       - name: Run code linters
         uses: reviewdog/action-golangci-lint@v2
@@ -114,20 +111,19 @@ jobs:
 
       - name: Run go-consistent
         env:
-          COMMAND: 'bin/go-consistent -pedantic -exclude "tests" ./...'
-          REDIRECT: "| bin/reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error=true"
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
         run: |
-          if out=$( ${{ env.COMMAND }} ); exit_code=$?; [ $exit_code -ne 0 ]; then
-            if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
-              echo "$out"
-              exit $exit_code
-            else
-              echo "$out" ${{ env.REDIRECT }}
-            fi
-          else
+          if out=$(bin/go-consistent -pedantic -exclude "tests" ./...); exit_code=$?; [ $exit_code -eq 0 ]; then
             echo "$out"
+            exit 0
           fi
+
+          if [ $exit_code -gt 1 ] || ${{ github.event.pull_request == null }}; then
+            echo "$out"
+            exit $exit_code
+          fi
+
+          echo "$out" | bin/reviewdog -f=go-consistent -reporter=github-pr-review -fail-on-error=true
 
       - name: Test common API
         run: make test-common
